# Write your MySQL query statement below
SELECT P.PRODUCT_NAME, SUM(O.UNIT) AS UNIT
FROM ORDERS O INNER JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.ORDER_DATE >= '2020-02-01' AND O.ORDER_DATE < '2020-03-01'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
HAVING SUM(O.UNIT)>=100;